### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by ruzekle** [0bebet/HaxeBird#1]
characters 7-37 : Class not found : flixel.text.FlxBitmapTextField

I'm running with dev repos

**Comment by 0bebet** [comment]
Haxe dev repos or HaxeFlixel? And for which platform are you building?

**Comment by ruzekle** [comment]
haxeflixel dev repos: I have version 3.3.6
I'm building for Linux

**Comment by 0bebet** [comment]
don't know why but dev repos does not have that class while master has it. I try to fix immediately

**Comment by 0bebet** [comment]
Fixed. Please, use HaxeBird dev repos while you use dev from HaxeFlixel
